const quotes = [
    ["If you are going through hell, keep going.", "Winston S. Churchill"],
    ["Rivers know this: there is no hurry. We shall get there some day.", "A.A. Milne, Winnie-the-Pooh"],
    ["It does not matter how slowly you go as long as you do not stop.", "Confucius"],
    ["You may encounter many defeats, but you must not be defeated. In fact, it may be necessary to encounter the defeats, so you can know who you are, what you can rise from, how you can still come out of it.", "Maya Angelou"],
    ["Never lose hope. Storms make people stronger and never last forever.", "Roy T. Bennett, The Light in the Heart"],
    ["The brick walls are there for a reason. The brick walls are not there to keep us out. The brick walls are there to give us a chance to show how badly we want something. Because the brick walls are there to stop the people who don’t want it badly enough. They’re there to stop the other people.", "Randy Pausch, The Last Lecture"],
    ["Sometimes even to live is an act of courage.", "Lucius Annaeus Seneca"],
    ["There are times to stay put, and what you want will come to you, and there are times to go out into the world and find such a thing for yourself.", "Lemony Snicket, Horseradish"],
    ["The man who moves a mountain begins by carrying away small stones.", "Confucius, Confucius: The Analects"],
    ["Never, never, never give in!", "Winston S. Churchill"],
    ["It always seems impossible until it's done.", "Nelson Mandela"],
    ["If you can keep your head when all about you", "Are losing theirs and blaming it on you,"],
    ["All of old. Nothing else ever. Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.", "Samuel Beckett, Worstward Ho"],
    ["It is not enough that we do our best; sometimes we must do what is required.", "Winston S. Churchill"],
    ["So comes snow after fire, and even dragons have their endings.", "J.R.R. Tolkien, The Hobbit, or There and Back Again"],
    ["Should you shield the canyons from the windstorms you would never see the true beauty of their carvings.", "Elisabeth Kübler-Ross"],
    ["Many of life's failures are people who did not realize how close they were to success when they gave up.", "Thomas A. Edison"],
    ["Courage doesn't always roar. Sometimes courage is the little voice at the end of the day that says I'll try again tomorrow.", "Mary Anne Radmacher"],
    ["I am a slow walker, but I never walk back.", "Abraham Lincoln"],
    ["Real courage is when you know you're licked before you begin, but you begin anyway and see it through no matter what.", "Harper Lee, To Kill a Mockingbird"],
    ["Never confuse a single defeat with a final defeat.", "F. Scott Fitzgerald"],
    ["A wise man will make more opportunities than he finds.", "Francis Bacon, The Essays"],
    ["Never give in. Never give in. Never, never, never, never—in nothing, great or small, large or petty—never give in, except to convictions of honour and good sense. Never yield to force. Never yield to the apparently overwhelming might of the enemy.", "Winston Churchill, Never Give In!: The Best of Winston Churchill's Speeches"],
    ["Just because you fail once doesn't mean you're gonna fail at everything.", "Marilyn Monroe"],
    ["Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree.", "Martin Luther"],
    ["You never know what's around the corner. It could be everything. Or it could be nothing. You keep putting one foot in front of the other, and then one day you look back and you've climbed a mountain.", "Tom Hiddleston"],
    ["Live the Life of Your Dreams", "When you start living the life of your dreams, there will always be obstacles, doubters, mistakes and setbacks along the way. But with hard work, perseverance and self-belief there is no limit to what you can achieve."],
    ["Let me not pray to be sheltered from dangers,", "but to be fearless in facing them."],
    ["If you fell down yesterday, stand up today.", "H.G. Wells"],
    ["Continuous effort - not strength or intelligence - is the key to unlocking our potential.", "Winston S. Churchill"],
    ["The lotus is the most beautiful flower, whose petals open one by one. But it will only grow in the mud. In order to grow and gain wisdom, first you must have the mud --- the obstacles of life and its suffering. ... The mud speaks of the common ground that humans share, no matter what our stations in life. ... Whether we have it all or we have nothing, we are all faced with the same obstacles: sadness, loss, illness, dying and death. If we are to strive as human beings to gain more wisdom, more kindness and more compassion, we must have the intention to grow as a lotus and open each petal one by one. ", "Goldie Hawn"],
    ["Dripping water hollows out stone, not through force but through persistence.", "Ovid"],
    ["The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", "Vince Lombardi"],
    ["Always bear in mind that your own resolution to succeed is more important than any one thing.", "Abraham Lincoln"],
    ["When things go wrong, don't go with them.", "Elvis Presley"],
    ["Every strike brings me closer to the next home run.", "Babe Ruth"],
    ["Go back?\" he thought. \"No good at all! Go sideways? Impossible! Go forward? Only thing to do! On we go!\" So up he got, and trotted along with his little sword held in front of him and one hand feeling the wall, and his heart all of a patter and a pitter.", "J.R.R. Tolkien, The Hobbit, or There and Back Again"],
    ["I have walked that long road to freedom. I have tried not to falter; I have made missteps along the way. But I have discovered the secret that after climbing a great hill, one only finds that there are many more hills to climb. I have taken a moment here to rest, to steal a view of the glorious vista that surrounds me, to look back on the distance I have come. But I can only rest for a moment, for with freedom come responsibilities, and I dare not linger, for my long walk is not ended.", "Nelson Mandela"],
    ["The three great essentials to achieve anything worthwhile are, first, hard work; second, stick-to-itiveness; third, common sense.", "Thomas A. Edison"],
    ["Hardships make or break people.", "Margaret Mitchell, Gone with the Wind"],
    ["When you come to the end of your rope, tie a knot and hang on.", "Franklin D. Roosevelt"],
    ["It's not how we fall. It's how we get back up again.", "Patrick Ness, Monsters of Men"],
    ["I wish to weep", "but sorrow is"],
    ["Courage is not having the strength to go on; it is going on when you don't have the strength.", "Teddy Roosevelt"],
    ["Things don't go wrong and break your heart so you can become bitter and give up. They happen to break you down and build you up so you can be all that you were intended to be.", "Charles Jones, Life is Tremendous"],
    ["It doesn’t matter how many times you get knocked down. All that matters is you get up one more time than you were knocked down.", "Roy T. Bennett"],
    ["Failure is a bend in the road, not the end of the road. Learn from failure and keep moving forward.", "Roy T. Bennett"],
    ["My own heroes are the dreamers, those men and women who tried to make the world a better place than when they found it, whether in small ways or great ones. Some succeeded, some failed, most had mixed results... but it is the effort that's heroic, as I see it. Win or lose, I admire those who fight the good fight.", "George R.R. Martin"],
    ["We’re all going to keep fighting, Harry. You know that?", "J.K. Rowling, Harry Potter and the Deathly Hallows"],
    ["That's one of the remarkable things about life. It's never so bad that it can't get worse.", "Bill Watterson"],
    ["Whatever gets you through the night", "John Lennon"],
    ["What's the bravest thing you ever did?", "He spat in the road a bloody phlegm. Getting up this morning, he said."],
    ["Once you learn to quit, it becomes a habit.", "Vince Lombardi"],
    ["Your first 10,000 photographs are your worst.", "Henri Cartier-Bresson"],
    ["Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.", "Dale Carnegie"],
    ["Certain motherfuckers think they can fuck with my shit, but you can't kill the Rooster. You might can fuck him up some times, but, bitch, nobody kills the motherfucking Rooster. You know what I'm saying?", "David Sedaris, Me Talk Pretty One Day"],
    ["...A man can only stumble for so long before he either falls or stands up straight.", "Brandon Sanderson, The Well of Ascension"],
    ["A bend in the road is not the end of the road…Unless you fail to make the turn.", "Helen Keller"],
    ["I am extraordinarily patient, provided I get my own way in the end.", "Margaret Thatcher"],
    ["Pain is temporary. It may last a minute, or an hour, or a day, or a year, but eventually it will subside and something else will take its place. If I quit, however, it lasts forever. That surrender, even the smallest act of giving up, stays with me. So when I feel like quitting, I ask myself, which would I rather live with?", "Lance Armstrong, It's Not about the Bike: My Journey Back to Life"],
    ["Remember to look up at the stars and not down at your feet. Try to make sense of what you see and wonder about what makes the universe exist. Be curious. And however difficult life may seem, there is always something you can do and succeed at.", "It matters that you don't just give up."],
    ["Persistence. Perfection. Patience. Power. Prioritize your passion. It keeps you sane.", "Criss Jami, Killosophy"],
    ["You may have to fight a battle more than once to win it.", "Margaret Thatcher"],
    ["Keep passing the open windows.", "John Irving, The Hotel New Hampshire"],
    ["It does not matter how slowly you go so long as you do not stop.", "Andy Warhol"],
    ["Women are never so strong as after their defeat.", "Alexandre Dumas, Queen Margot, or Marguerite de Valois"],
    ["A bridge of silver wings stretches from the dead ashes of an unforgiving nightmare", "to the jeweled vision of a life started anew."],
    ["It’s probably my job to tell you life isn’t fair, but I figure you already know that. So instead, I’ll tell you that hope is precious, and you’re right not to give up.", "C.J. Redwine, Defiance"],
    ["Courage does not always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.", "Mary Anne Radmacher"],
    ["The harder you fall, the heavier your heart; the heavier your heart, the stronger you climb; the stronger you climb, the higher your pedestal.", "Criss Jami, Killosophy"],
    ["I tried always to do better: saw always a little further. I tried to stretch myself.", "Audrey Hepburn"],
    ["After climbing a great hill, one only finds that there are many more hills to climb.", "Nelson Mandela"],
    ["The writer's curse is that even in solitude, no matter its duration, he never grows lonely or bored.", "Criss Jami, Killosophy"],
    ["By perseverance the snail reached the ark.", "Charles Spurgeon"],
    ["Success is a little like wrestling a gorilla. You don't quit when you're tired. You quit when the gorilla is tired.", "Robert Strauss"],
    ["To reach a port we must set sail –", "Sail, not tie at anchor"],
    ["Character consists of what you do on the third and fourth tries.", "James A. Michener"],
    ["I am not concerned that you have fallen -- I am concerned that you arise.", "Abraham Lincoln"],
    ["Every day you may make progress. Every step may be fruitful. Yet there will stretch out before you an ever-lengthening, ever-ascending, ever-improving path. You know you will never get to the end of the journey. But this, so far from discouraging, only adds to the joy and glory of the climb.", "Winston S. Churchill"],
    ["Courage and perseverance have a magical talisman, before which difficulties disappear and obstacles vanish into air.", "John Quincy Adams"],
    ["Even in the mud and scum of things, something always, always sings.", "Ralph Waldo Emerson"],
    ["What helps you persevere is your resilience and commitment.", "Roy T. Bennett, The Light in the Heart"],
    ["Children have a lesson adults should learn, to not be ashamed of failing, but to get up and try again. Most of us adults are so afraid, so cautious, so 'safe,' and therefore so shrinking and rigid and afraid that it is why so many humans fail. Most middle-aged adults have resigned themselves to failure.", "Malcolm X, The Autobiography of Malcolm X"],
    ["I think this is when most people give up on their stories. They come out of college wanting to change the world, wanting to get married, wanting to have kids and change the way people buy office supplies. But they get into the middle and discover it was harder than they thought. They can't see the distant shore anymore, and they wonder if their paddling is moving them forward. None of the trees behind them are getting smaller and none of the trees ahead are getting bigger. They take it out on their spouses, and they go looking for an easier story.", "Donald Miller, A Million Miles in a Thousand Years: What I Learned While Editing My Life"],
    ["It's not what we do once in a while that shapes our lives. It's what we do consistently.", "Anthony Robbins"],
    ["Life is, in fact, a battle. Evil is insolent and strong; beauty enchanting, but rare; goodness very apt to be weak; folly very apt to be defiant; wickedness to carry the day; imbeciles to be in great places, people of sense in small, and mankind generally unhappy. But the world as it stands is no narrow illusion, no phantasm, no evil dream of the night; we wake up to it, forever and ever; and we can neither forget it nor deny it nor dispense with it.", "Henry James, Theory of Fiction: Henry James"],
    ["In essence, if we want to direct our lives, we must take control of our consistent actions. It's not what we do once in a while that shapes our lives, but what we do consistently.", "Anthony Robbins"],
    ["In order to share one's true brilliance one initially has to risk looking like a fool: genius is like a wheel that spins so fast, it at first glance appears to be sitting still.", "Criss Jami, Venus in Arms"],
    ["If we walk far enough,\" says Dorothy, \"we shall sometime come to someplace.", "L. Frank Baum, The Wonderful Wizard of Oz"],
    ["Giving up is the only sure way to fail.", "Gena Showalter"],
    ["What is the victory of a cat on a hot tin roof?—I wish I knew... Just staying on it, I guess, as long as she can...", "Tennessee Williams, Cat on a Hot Tin Roof"],
    ["...remember that what has once been done may be done again.", "Alexandre Dumas, The Count of Monte Cristo"],
    ["The only guarantee for failure is to stop trying", "John C. Maxwell"],
    ["If you can quit, then quit. If you can't quit, you're a writer.", "R.A. Salvatore"],
    ["The man who is swimming against the stream knows the strength of it.", "Woodrow Wilson"],
    ["He whines, he complains, he ducks out of the most obvious responsibility. He is vain, petty and maddening, but he doesn't ever quit.", "Megan Whalen Turner, The King of Attolia"],
    ["To remain indifferent to the challenges we face is indefensible. If the goal is noble, whether or not it is realized within our lifetime is largely irrelevant. What we must do therefore is to strive and persevere and never give up.", "Dalai Lama XIV"],
    ["I am sore wounded but not slain", "I will lay me down and bleed a while"],
    ["The person who doesn't scatter the morning dew will not comb grey hairs", "Hunter S. Thompson"],
    ["Every pain is a lesson.", "Frank Delaney, The Matchmaker of Kenmare"],
    ["My proceeds from the PayPal acquisition were $180 million. I put $100 million in SpaceX, $70m in Tesla, and $10m in Solar City. I had to borrow money for rent.", "Elon Musk"],
    ["Everyone has the fire, but the champions know when to ignite the spark.", "Amit Ray, Enlightenment Step by Step"],
    ["It's easier to start over than to work to make something last.", "Rachel Hawthorne, Thrill Ride"],
    ["The only kinds of fights worth fighting are those you’re going to lose, because somebody has to fight them and lose and lose and lose until someday, somebody who believes as you do wins.", "I.F. Stone"],
    ["Intelligence entails a strong mind, but genius entails a heart of a lion in tune with a strong mind.", "Criss Jami, Diotima, Battery, Electric Personality"],
    ["The crazy creatives are the creatives who never go completely mad. They aren't so easily disheartened by the seemingly endless amounts of scrutiny that creative individuals tend to receive because they, like insanity, are the ones who feed off of opposition and negative feedback and manage to continue along with a healthy ambition. It is the crazy that teaches us to use our gifts wisely and own all the attackers.", "Criss Jami, Diotima, Battery, Electric Personality"],
    ["First steps are always the hardest but until they are taken the notion of progress remains only a notion and not an achievement.", "Aberjhani, Illuminated Corners: Collected Essays and Articles Volume I."],
    ["There are always periodic opportunities to give up, while every single moment is an opportunity to persevere.", "Dean F. Wilson"],
    ["First, I thought, almost despairing,", "This must crush my spirit now;"],
    ["With ordinary talent and extraordinary perseverance, all things are attainable", "Thomas Fowell Buxton"],
    ["You mustn't get so upset about what you feel, Spud. No one's a hundred per cent consistent all the time. We might like to be. We can plan our lives along certain lines. But you know, there's no future in screwing down all the pressure valves and smashing in the gauge. You can do it for a bit and then something goes. Sometimes it gets that the only thing is just to say, 'That's what I'd like to feel twenty-four hours a day; but, the hell with it, this is how I feel now.", "Mary Renault, The Charioteer"],
    ["When your only regret is if anyone thinks you regret anything - that is the definition of conviction.", "Criss Jami, Diotima, Battery, Electric Personality"],
    ["The world is full of painful stories. Sometimes it seems as though there aren't any other kind and yet I found myself thinking how beautiful that glint of water was through the trees.", "Octavia E. Butler, Parable of the Sower"],
    ["Disciplined runners consistently clear their heads and focus fully on the journey ahead.. .because their passion and zeal for the goal supersedes the strain. The goal beckons them onward. Passion doesn't negate weariness; it just resolves to press beyond it.", "Priscilla Shirer, Gideon: Your Weakness. God's Strength."],
    ["Every step was a victory. He had to remember that.", "George Saunders, Tenth of December"],
    ["Life is like crossing a river. If you take a huge step-aim for too bigger dreams-then the current will knock you off your feet and carry you away.", "The way to do it is small steps, you will take hold of life. You will get there in the end."],
    ["Some lean back. But those who lean forward are poised to cross the finish-line, first!", "T.F. Hodge, From Within I Rise: Spiritual Triumph Over Death and Conscious Encounters with \"The Divine Presence\""],
    ["Nothing earthly will make me give up my work in despair.", "David Livingstone"],
    ["One bulb at a time. There was no other way to do it. No shortcuts--simply loving the slow process of planting. Loving the work as it unfolded. Loving an achievement that grew slowly and bloomed for only three weeks each year.", "Jaroldeen Asplund Edwards, The Daffodill Principle"],
    ["Sometimes what seems so right turns out wrong and what seems so wrong turns out right. What do I call this phenomenon? Life.", "Charles F. Glassman, Brain Drain The Breakthrough That Will Change Your Life"]
];

const getQuote = () => {
    const quote = quotes[Math.floor((Math.random() * quotes.length))]
    return `"${quote[0]}" - ${quote[1]}`
};

export { getQuote };
